### PR TITLE
Generic FieldItemListInterface and related stubs

### LINKED ISSUE #353: Type from FieldItemListInterface iterator odd behaviour
Since updating from 1.1.10 to 1.1.11 a small thing forced me to add additional typehinting to satisfy phpstan w/ level 8.

Code sample stripped of irrelevant logic:

```php
public function viewElements(FieldItemListInterface $items, $langcode = NULL) {
  return array_map(function (StringItem $item) {
    // Do something...
    return $item->getValue();
  }, iterator_to_array($items));
```

This sample now raises this error:

> Parameter #1 $callback of function array_map expects (callable(Drupal\Core\TypedData\TypedDataInterface): mixed)|null, Closure(Drupal\Core\Field\Plugin\Field\FieldType\StringItem): mixed given.

To work around this error I updated the code snippet to roughly:

```php
public function viewElements(FieldItemListInterface $items, $langcode = NULL) {
  /** @var \Drupal\Core\Field\Plugin\Field\FieldType\StringItem[] $stringItems */
  $stringItems = iterator_to_array($items);
  return array_map(function (StringItem $item) {
    // Do something...
    return $item->getValue();
  }, $stringItems);
```

Not sure what to do about this, whether its intentional, or if we can add extra intelligence to phpstan-drupal.

### PR DESCRIPTION
**Pull request by jacktonkin**
Recent stub additions conflicted with some stubs in my website project so sharing here.

I have a lot of annotations like `@property EntityReferenceFieldItemListInterface<UserInterface> $owner` on custom entities so PHPStan knows the type of `$entity->owner->entity` and so on.

Happy to try and help split into smaller PRs and take direction on testing.

This is related to #353 and may also allow some extension code to go away?

Fixes https://github.com/mglaman/phpstan-drupal/issues/432

### CODE REVIEW

**Comment by mglaman** [comment]
Ready to merge, I just want some other community feedback quick to forgo writing a bunch of tests right now.

**Review by mglaman — APPROVED** [review]

**Comment by mglaman** [comment]
tagging @brambaud and @dpi for review

**Comment by brambaud** [comment]
Looks good to me!

Awesome 🤩

**Comment by mglaman** [comment]
MERGING! I didn't put this in 1.1.22 as I wanted to ship some other fixes. But this will be in 1.1.23!

**Pull request merged**
