### PR TITLE
TestClassSuffixNameRule

### PR DESCRIPTION
**Pull request by Boegie**
Trying to implement #608

### CODE REVIEW

**Comment by Boegie** [comment]
Let's wait until somebody comments on https://www.drupal.org/project/drupal/issues/3268489#comment-15252653 about the  `abstract`-ness of `*TestBase` classes.

**Comment by Boegie** [comment]
Verdict is in:

> The base classes should always be abstract yes, not sure whether it's documented but it's what should happen.
_catch in https://www.drupal.org/project/drupal/issues/3268489#comment-15252749_

For me the rule works as expected and is ready for review.

**Comment by mglaman** [comment]
@Boegie I'll defer to your judgement if the baseline failures look OK. When you say it's good, I'll merge

**Comment by Boegie** [comment]
Ohh, the pressure... ;)

Thanks @mglaman, I have something cooking locally that has three rules for test classes, one for the class name (this one), one for the namespace and one for the file location.

Since they both use a lot of the same code it makes sense to me to create a base class for this, thus trying to create one PR to rule them all. 

Shouldn't be long...
_#FamousLastWords_

**Pull request merged**
